### ISSUE TITLE
【依頼】ProtoSpace挙動確認

### ISSUE THREAD

**Issue by Nobutaka333** [Nobutaka333/protospace-34825#1]
# URL
https://protospace-34825.herokuapp.com/

**Comment by odada1117** [comment]
ご提出ありがとうございます。
動作の確認をしたところ、編集機能に関して修正していただきたい箇所が2箇所ございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] 何も編集せずに更新をしても、画像無しのプロトタイプにならないこと
   →現状、エラーが出ています。

- [x] 空の入力欄がある場合は、編集できずにそのページに留まること
   →現状、エラーが出ています。

<img width="589" alt="スクリーンショット 2021-03-13 11 01 32" src="https://user-images.githubusercontent.com/79196482/111091524-893c5600-8576-11eb-952c-01e24ab51c0d.png">



修正が完了しましたら、再度以下のprotospace完了報告フォームのご提出お願いします！
※新しいissueを作っていただく必要はございません。
https://forms.gle/ZdLeprTTWhMA8aZA7

**Comment by Nobutaka333** [comment]
お忙しい中ご確認ありがとうございます。
修正を行いましたので、改めてご確認をよろしくお願いいたします。

**Comment by odada1117** [comment]
早速の修正、ご提出ありがとうございます。
問題なく正常に動作することが確認できました！LGTMです！
おめでとうございます🎉

次はいよいよ最終課題ですね！今まで学習したことを活かして進めていきましょう（^^）
別途、最終課題の案内をチャンネルに送らせて頂きます。
今しばらくお待ちください🍀
